# Config file for automatic testing at travis-ci.org

language: python
dist: xenial
python:
    - "3.8"

env:
    global:
        - PIPENV_VENV_IN_PROJECT=1
        - PIPENV_IGNORE_VIRTUALENVS=1

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - make clean
    - pip install pipenv
    pipenv install --dev --three

# Command to run tests, e.g. python setup.py test
script: pipenv run tox
