# Config file for automatic testing at travis-ci.org

dist: xenial
language: python
python:
    - "3.7.3"
    - "3.8.0"

branches:
  only:
    - master
    - develop

# Command to install dependencies
install:
  - pip3 install tox-travis

# Command to run tests
script: tox
